linters:
  enable:
  - asciicheck
  - errcheck
  - errorlint
  - gofmt
  - goimports
  - gosec
  - gocritic
  - importas
  - prealloc
  - revive
  - misspell
  - stylecheck
  - tparallel
  - unconvert
  - unparam
  - unused
  - whitespace
output:
  uniq-by-line: false
run:
  issues-exit-code: 1
  timeout: 10m
  skip-dirs:
    - internal/third_party
