name: tests
on:
  push:
    branches: ['main']
    paths-ignore:
      - "docs/*"
      - "**.md"
  pull_request:
    paths-ignore:
      - "docs/*"
      - "**.md"
permissions: read-all
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ['1.25', '1.26']
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        persist-credentials: false
    - name: Install Go
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
      with:
        go-version: ${{ matrix.go-version }}
        cache: true
    - name: Test
      run: go test -race -timeout 20m ./...
  test-freebsd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@7ca82f79fe3078fecded6d3a2bff094995447bbd
      with:
        usesh: true
        prepare: |
        run: |
          pkg update -f
          pkg install -y git wget

          wget https://go.dev/dl/go1.26.1.freebsd-amd64.tar.gz
          tar -C /usr/local -xzf go1.26.1.freebsd-amd64.tar.gz

          /usr/local/go/bin/go test -race -timeout 20m ./...
