name: gittuf Verification
on:
  push:
    branches: ['main']
permissions: read-all
jobs:
  gittuf-verify:
    if: github.repository == 'gittuf/gittuf'
    runs-on: ubuntu-latest
    steps:
      - name: Install gittuf
        uses: gittuf/gittuf-installer@da8c392f92d2f7f2e50db8457951395bfb593e15
      - name: Checkout and verify repository
        run: |
          sleep 10s
          gittuf clone https://github.com/${{ github.repository }}
          cd gittuf
          gittuf verify-ref main --verbose
