name: remote tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ['1.23']

    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

    - name: Set up Git
      run: |
        sudo apt-get update
        sudo apt-get install -y git

    - name: Set up GitHub SSH key (if using SSH)
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GITHUB_DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Build project
      run: make

    - name: Run integration tests
      run: |
        chmod +x .github/workflows/runtests.py
        python .github/workflows/runtests.py
