name: remote tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ['1.23']
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: Install Go
      uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a
      with:
        go-version: ${{ matrix.go-version }}

    - name: Set up GitHub SSH key (if using SSH)
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GITHUB_DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Build project
      run: make

    - name: Run integration tests
      run: |
        chmod +x .github/workflows/runtests.py
        python .github/workflows/runtests.py
