name: remote tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ['1.23']
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: Install Go
      uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build gittuf
      run: make just-install

    - name: Run integration tests
      run: |
        chmod +x .github/workflows/runtests3.py
        python .github/workflows/runtests3.py
