name: git 2.34.1 on ubuntu-22.04
on:
  push:
    branches: ["main"]
    paths-ignore:
      - "docs/**"
      - "**.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**.md"
permissions: read-all
jobs:
  test:
    strategy:
      matrix:
        go-version: ['1.25', '1.26']
    runs-on: ubuntu-22.04
    steps:
      - name: Downgrade Git
        run: sudo apt-get update && sudo apt-get install -y --allow-downgrades git=1:2.34.1-1ubuntu1.17 git-man=1:2.34.1-1ubuntu1.17
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - name: Install Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      - name: Test
        run: go test ./...
